### PR TITLE
Kaffys.yaml

### PR DESCRIPTION
**Pull request by Kaffys**
this one is fixed now

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Please make sure that your `blog` and `feed` start with `http://`

**Comment by Nolski** [comment]
Think you could remove the empty keys such as `litreview7:`? Other than that this looks all good and I should be able to merge.

**Comment by decause** [comment]
@Kaffys empty entries may break things. I'd comment them out or remove them until you have something to post for each item.

**Comment by Kaffys** [comment]
I fixed the empty lines

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by decause** [comment]
:8ball:

**Pull request merged**
