### PR TITLE
add profiles 3 + 4, final post

### PR DESCRIPTION
**Pull request by wywin**
Now with gitbook!
:snowflake:

### CODE REVIEW

**Comment by wywin** [comment]
I don't even remember if we had to add the final post to yaml, but I saw other people doing it, so might as well.

**Comment by decause** [comment]
change <code>finalpost</code> to <code>finalanswers</code> and I'll merge.

**Comment by wywin** [comment]
:wrench: fix'd :wrench:

**Comment by decause** [comment]
:checkered_flag:

**Pull request merged**
