### PR TITLE
Added the actual location of the repo for the syllabus.

### PR DESCRIPTION
**Pull request by jeid64**

### CODE REVIEW

**Comment by decause** [comment]
@liam-middlebrook I thought we fixed this to pull from the <code>repo</code> key in <code>site.yaml</code>?

**Comment by decause** [comment]
@liam-middlebrook where we at on this one?

**Comment by decause** [comment]
@liam-middlebrook any updates?

**Comment by liam-middlebrook** [comment]
Yeah, sorry about taking awhile to get to this. 

@jeid64 you should have it point to `${course['repo']}` rather than a hardcoded url.

**Comment by decause** [comment]
@jeid64 yes, agreed. Change as @liam-middlebrook said and I'll merge.

**Comment by liam-middlebrook** [comment]
@jeid64 status on this?

**Comment by decause** [comment]
gonna close this, unless @jeid64 has a fix for it?

**Pull request closed without merging**
