### PR TITLE
added missing links

### PR DESCRIPTION
**Pull request by ajman1101**

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Please fix your [YAML errors](https://travis-ci.org/decause/bizlegfoss/builds/62471736)

**Comment by msoucy** [comment]
Also, the key is "preso1", not "presso1"...

**Comment by decause** [comment]
@ajman1101 see above comments.

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by decause** [comment]
:checkered_flag:

**Pull request merged**
