### PR TITLE
hw1

### PR DESCRIPTION
**Pull request by Kaffys**
homework 1

### CODE REVIEW

**Comment by decause** [comment]
@Kaffys be sure to <code>git pull<code> and merge upstream changes

**Comment by decause** [comment]
@Kaffys 

<code>git remote add upstream git@github.com:decause/bizlegfoss.git</code>
<code>git pull upstream master</code>
<code>git push origin master</code>

**Comment by decause** [comment]
@Kaffys come and see me or get help in IRC merging upstream.

**Comment by decause** [comment]
@Kaffys still got issues here... plz seek assistance :checkered_flag:

**Comment by decause** [comment]
@kaffys when you get back from GDC, we're going to nip this in the bud.

**Comment by Kaffys** [comment]
Aj and I went through it and I thought we fixed it. But yeah we can sit down before class one day

Kathleen Ann Tigue
RIT - Game Design and Development
(516) 303 - 6026

**Comment by decause** [comment]
@Kaffys I'm going to close this pull request, as it seems like a big mess at this point. When you're back from break, we're going to actually sit down and figure this out. For now, I'm going to fix your .yaml file manually. Be sure to <code>git pull</code> from my repo and merge.

**Pull request closed without merging**
