### PR TITLE
Update jeid64.yaml

### PR DESCRIPTION
**Pull request by jeid64**
Added final.

### CODE REVIEW

**Comment by decause** [comment]
change <code>finalpost</code> to <code>finalanswers</code> and I'll merge.

**Comment by jeid64** [comment]
GTG LGTM :+1: :smiley_cat: :miley_cyrus: Can't stop won't stop miley tour 2012

**Comment by liam-middlebrook** [comment]
:hammer: lgtm merge asap :wrench:

**Comment by decause** [comment]
:checkered_flag:

**Pull request merged**
