### PR TITLE
Finally done

### PR DESCRIPTION
**Pull request by Kaffys**
🎓🎓🎓🎓🎓🎓🎓🎓🎓

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Please change `finalanwers` to `finalanswers`

**Comment by liam-middlebrook** [comment]
#rekt

**Comment by Nolski** [comment]
:grapes:

**Comment by decause** [comment]
Even with two entries for <code>litreview8</code> I'll merge and fix manually later.

**Pull request merged**
